---
title: Preamble
format:
  html:
    toc: true
    number-sections: false
---

There currently exists 417 datasets in the UFF format. The complete UFF library and their descriptions can be found on the website of the [University of Cincinnati](https://www.ceas3.uc.edu/sdrluff/all_files.php). `UFFio.jl` only implements a subset of these datasets that are commonly used in structural dynamics and modale analysis.

As mentioned in the [Home page](../index.qmd), the UFF datasets implemented in `UFFio.jl` are:

- [Dataset 15 - Nodes](dataset15.qmd)
- [Dataset 18 - Coordinate systems](dataset18.qmd)
- [Dataset 55 - Data at nodes](dataset55.qmd)
- [Dataset 58 - Function at nodal DOF](dataset58.qmd)
- [Dataset 82 - Tracelines](dataset82.qmd)
- [Dataset 151 - Header](dataset151.qmd)
- [Dataset 164 - Units](dataset164.qmd)
- [Dataset 2411 - Nodes - Double precision](dataset2411.qmd)
- [Dataset 2412 - Elements](dataset2412.qmd)
- [Dataset 2414 - Analysis Data](dataset2414.qmd)

Each dataset page contains a description of the dataset as well as its API documentation.