project:
  type: website

website:
  title: "UFF.jl"
  favicon: "assets/logo/doclogo.svg"
  page-navigation: true
  navbar:
    logo: "assets/logo/doclogo.svg"
    left:
      - text: "Overview"
        file: index.qmd
      - text: "Usage"
        file: usage/index.qmd
      - text: "Datasets"
        file: datasets/index.qmd
      - text: "Helper functions"
        file: helper/index.qmd
    right:
      - icon: github
        href: https://github.com/maucejo/UFF.jl
        aria-label: GitHub

  sidebar:
    - title: "Overview"
      contents:
        - index.qmd
        - overview/installation.qmd
        - overview/release_notes.qmd

    - title: "Usage"
      contents:
        - usage/index.qmd

    - title: "Datasets"
      contents:
        - datasets/index.qmd
        - datasets/dataset15.qmd
        - datasets/dataset18.qmd
        - datasets/dataset55.qmd
        - datasets/dataset58.qmd
        - datasets/dataset82.qmd
        - datasets/dataset151.qmd
        - datasets/dataset164.qmd
        - datasets/dataset2411.qmd
        - datasets/dataset2412.qmd
        - datasets/dataset2414.qmd

    - title: "Helper functions"
      contents:
        - helper/index.qmd

  page-footer:
    center: "2025 Mathieu Aucejo &#8729; Powered by [![](/assets/logo/quarto.png){width=4mm}](https://quarto.org) and [![](/assets/logo/julia.svg){width=4mm}](https://julialang.org)"

format:
  html:
    theme:
      - cosmo
      - assets/doctheme.scss
    smooth-scroll: true