# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "cdc6534d15c49747ddb580f3a361a587447f9eb2"

[[deps.UFFReader]]
path = "/Users/maucejo/Documents/01_Recherche/04_Projets/Codes/Julia/UFFReader"
uuid = "20c5726e-8372-4c34-be2c-190a5a70d483"
version = "0.1.0"
