# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "9a001dd2e2b3ceeb2b4f37abc9a2fa1b695f8c74"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.UFFFiles]]
deps = ["Printf"]
path = "/Users/maucejo/Documents/01_Recherche/04_Projets/Codes/Julia/UFFFiles"
uuid = "20c5726e-8372-4c34-be2c-190a5a70d483"
version = "0.1.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"
