# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "9c586a6cf4fffb58987b4ab29de90edde71d3b5c"

[[deps.UniversalFileFormat]]
path = "/Users/maucejo/Documents/01_Recherche/04_Projets/Codes/Julia/UniversalFileFormat"
uuid = "20c5726e-8372-4c34-be2c-190a5a70d483"
version = "0.1.0"
